# Feature Engineering

## Import Library

In [1]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.feature_selection import SelectKBest, chi2
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.datasets import load_wine

In [2]:
data = load_wine()
print(data)
X, y = data.data, data.target

{'data': array([[1.423e+01, 1.710e+00, 2.430e+00, ..., 1.040e+00, 3.920e+00,
        1.065e+03],
       [1.320e+01, 1.780e+00, 2.140e+00, ..., 1.050e+00, 3.400e+00,
        1.050e+03],
       [1.316e+01, 2.360e+00, 2.670e+00, ..., 1.030e+00, 3.170e+00,
        1.185e+03],
       ...,
       [1.327e+01, 4.280e+00, 2.260e+00, ..., 5.900e-01, 1.560e+00,
        8.350e+02],
       [1.317e+01, 2.590e+00, 2.370e+00, ..., 6.000e-01, 1.620e+00,
        8.400e+02],
       [1.413e+01, 4.100e+00, 2.740e+00, ..., 6.100e-01, 1.600e+00,
        5.600e+02]]), 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
 

In [3]:
df = pd.DataFrame(X, columns=data.feature_names)
df['target'] = y

df

alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
0      14.23        1.71  2.43               15.6      127.0           2.80   
1      13.20        1.78  2.14               11.2      100.0           2.65   
2      13.16        2.36  2.67               18.6      101.0           2.80   
3      14.37        1.95  2.50               16.8      113.0           3.85   
4      13.24        2.59  2.87               21.0      118.0           2.80   
..       ...         ...   ...                ...        ...            ...   
173    13.71        5.65  2.45               20.5       95.0           1.68   
174    13.40        3.91  2.48               23.0      102.0           1.80   
175    13.27        4.28  2.26               20.0      120.0           1.59   
176    13.17        2.59  2.37               20.0      120.0           1.65   
177    14.13        4.10  2.74               24.5       96.0           2.05   

     flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
0          3.06                  0.28             2.29             5.64  1.04   
1          2.76                  0.26             1.28             4.38  1.05   
2          3.24                  0.30             2.81             5.68  1.03   
3          3.49                  0.24             2.18             7.80  0.86   
4          2.69                  0.39             1.82             4.32  1.04   
..          ...                   ...              ...              ...   ...   
173        0.61                  0.52             1.06             7.70  0.64   
174        0.75                  0.43             1.41             7.30  0.70   
175        0.69                  0.43             1.35            10.20  0.59   
176        0.68                  0.53             1.46             9.30  0.60   
177        0.76                  0.56             1.35             9.20  0.61   

     od280/od315_of_diluted_wines  proline  target  
0                            3.92   1065.0       0  
1                            3.40   1050.0       0  
2                            3.17   1185.0       0  
3                            3.45   1480.0       0  
4                            2.93    735.0       0  
..                            ...      ...     ...  
173                          1.74    740.0       2  
174                          1.56    750.0       2  
175                          1.56    835.0       2  
176                          1.62    840.0       2  
177                          1.60    560.0       2  

[178 rows x 14 columns]

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 178 entries, 0 to 177
Data columns (total 14 columns):
 #   Column                        Non-Null Count  Dtype  
---  ------                        --------------  -----  
 0   alcohol                       178 non-null    float64
 1   malic_acid                    178 non-null    float64
 2   ash                           178 non-null    float64
 3   alcalinity_of_ash             178 non-null    float64
 4   magnesium                     178 non-null    float64
 5   total_phenols                 178 non-null    float64
 6   flavanoids                    178 non-null    float64
 7   nonflavanoid_phenols          178 non-null    float64
 8   proanthocyanins               178 non-null    float64
 9   color_intensity               178 non-null    float64
 10  hue                           178 non-null    float64
 11  od280/od315_of_diluted_wines  178 non-null    float64
 12  proline                       178 non-null    float64
 13  targe

In [5]:
df.describe(include='all')

alcohol  malic_acid         ash  alcalinity_of_ash   magnesium  \
count  178.000000  178.000000  178.000000         178.000000  178.000000   
mean    13.000618    2.336348    2.366517          19.494944   99.741573   
std      0.811827    1.117146    0.274344           3.339564   14.282484   
min     11.030000    0.740000    1.360000          10.600000   70.000000   
25%     12.362500    1.602500    2.210000          17.200000   88.000000   
50%     13.050000    1.865000    2.360000          19.500000   98.000000   
75%     13.677500    3.082500    2.557500          21.500000  107.000000   
max     14.830000    5.800000    3.230000          30.000000  162.000000   

       total_phenols  flavanoids  nonflavanoid_phenols  proanthocyanins  \
count     178.000000  178.000000            178.000000       178.000000   
mean        2.295112    2.029270              0.361854         1.590899   
std         0.625851    0.998859              0.124453         0.572359   
min         0.980000    0.340000              0.130000         0.410000   
25%         1.742500    1.205000              0.270000         1.250000   
50%         2.355000    2.135000              0.340000         1.555000   
75%         2.800000    2.875000              0.437500         1.950000   
max         3.880000    5.080000              0.660000         3.580000   

       color_intensity         hue  od280/od315_of_diluted_wines      proline  \
count       178.000000  178.000000                    178.000000   178.000000   
mean          5.058090    0.957449                      2.611685   746.893258   
std           2.318286    0.228572                      0.709990   314.907474   
min           1.280000    0.480000                      1.270000   278.000000   
25%           3.220000    0.782500                      1.937500   500.500000   
50%           4.690000    0.965000                      2.780000   673.500000   
75%           6.200000    1.120000                      3.170000   985.000000   
max          13.000000    1.710000                      4.000000  1680.000000   

           target  
count  178.000000  
mean     0.938202  
std      0.775035  
min      0.000000  
25%      0.000000  
50%      1.000000  
75%      2.000000  
max      2.000000

In [6]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=42)

In [7]:
print(X_test)

[[1.364000e+01 3.100000e+00 2.560000e+00 1.520000e+01 1.160000e+02
  2.700000e+00 3.030000e+00 1.700000e-01 1.660000e+00 5.100000e+00
  9.600000e-01 3.360000e+00 8.450000e+02]
 [1.421000e+01 4.040000e+00 2.440000e+00 1.890000e+01 1.110000e+02
  2.850000e+00 2.650000e+00 3.000000e-01 1.250000e+00 5.240000e+00
  8.700000e-01 3.330000e+00 1.080000e+03]
 [1.293000e+01 2.810000e+00 2.700000e+00 2.100000e+01 9.600000e+01
  1.540000e+00 5.000000e-01 5.300000e-01 7.500000e-01 4.600000e+00
  7.700000e-01 2.310000e+00 6.000000e+02]
 [1.373000e+01 1.500000e+00 2.700000e+00 2.250000e+01 1.010000e+02
  3.000000e+00 3.250000e+00 2.900000e-01 2.380000e+00 5.700000e+00
  1.190000e+00 2.710000e+00 1.285000e+03]
 [1.237000e+01 1.170000e+00 1.920000e+00 1.960000e+01 7.800000e+01
  2.110000e+00 2.000000e+00 2.700000e-01 1.040000e+00 4.680000e+00
  1.120000e+00 3.480000e+00 5.100000e+02]
 [1.430000e+01 1.920000e+00 2.720000e+00 2.000000e+01 1.200000e+02
  2.800000e+00 3.140000e+00 3.300000e-01 1.970000e+00

In [8]:
print(X_train)

[[1.434e+01 1.680e+00 2.700e+00 ... 5.700e-01 1.960e+00 6.600e+02]
 [1.253e+01 5.510e+00 2.640e+00 ... 8.200e-01 1.690e+00 5.150e+02]
 [1.237e+01 1.070e+00 2.100e+00 ... 1.040e+00 2.770e+00 6.600e+02]
 ...
 [1.438e+01 1.870e+00 2.380e+00 ... 1.200e+00 3.000e+00 1.547e+03]
 [1.269e+01 1.530e+00 2.260e+00 ... 9.600e-01 2.060e+00 4.950e+02]
 [1.234e+01 2.450e+00 2.460e+00 ... 8.000e-01 3.380e+00 4.380e+02]]


## Filter Methods

## SelectKBest

In [16]:
filter_selector = SelectKBest(score_func=chi2, k=2)

X_train_filter = filter_selector.fit_transform(X_train, y_train)
X_test_filter = filter_selector.transform(X_test)

print(X_test_filter)

print("Fitur yang dipilih dengan Filter Methods: ", filter_selector.get_support(indices=True))

[[5.100000e+00 8.450000e+02]
 [5.240000e+00 1.080000e+03]
 [4.600000e+00 6.000000e+02]
 [5.700000e+00 1.285000e+03]
 [4.680000e+00 5.100000e+02]
 [6.200000e+00 1.280000e+03]
 [1.280000e+00 5.640000e+02]
 [7.300000e+00 7.500000e+02]
 [2.650000e+00 6.800000e+02]
 [5.600000e+00 7.800000e+02]
 [3.520000e+00 8.450000e+02]
 [8.600000e+00 5.000000e+02]
 [4.280000e+00 1.035000e+03]
 [3.400000e+00 3.720000e+02]
 [7.300000e+00 1.310000e+03]
 [2.000000e+00 3.250000e+02]
 [3.080000e+00 4.340000e+02]
 [2.200000e+00 6.300000e+02]
 [7.220000e+00 1.045000e+03]
 [2.900000e+00 3.850000e+02]
 [8.700000e+00 1.680000e+03]
 [5.300000e+00 5.020000e+02]
 [3.270000e+00 6.800000e+02]
 [8.500000e+00 6.300000e+02]
 [9.899999e+00 4.700000e+02]
 [9.580000e+00 6.150000e+02]
 [2.060000e+00 3.450000e+02]
 [4.600000e+00 6.780000e+02]
 [2.400000e+00 4.800000e+02]
 [6.250000e+00 1.120000e+03]
 [4.700000e+00 1.035000e+03]
 [2.120000e+00 3.420000e+02]
 [4.000000e+00 8.300000e+02]
 [6.900000e+00 1.515000e+03]
 [5.600000e+00

In [17]:
print(X_test_filter)

[[5.100000e+00 8.450000e+02]
 [5.240000e+00 1.080000e+03]
 [4.600000e+00 6.000000e+02]
 [5.700000e+00 1.285000e+03]
 [4.680000e+00 5.100000e+02]
 [6.200000e+00 1.280000e+03]
 [1.280000e+00 5.640000e+02]
 [7.300000e+00 7.500000e+02]
 [2.650000e+00 6.800000e+02]
 [5.600000e+00 7.800000e+02]
 [3.520000e+00 8.450000e+02]
 [8.600000e+00 5.000000e+02]
 [4.280000e+00 1.035000e+03]
 [3.400000e+00 3.720000e+02]
 [7.300000e+00 1.310000e+03]
 [2.000000e+00 3.250000e+02]
 [3.080000e+00 4.340000e+02]
 [2.200000e+00 6.300000e+02]
 [7.220000e+00 1.045000e+03]
 [2.900000e+00 3.850000e+02]
 [8.700000e+00 1.680000e+03]
 [5.300000e+00 5.020000e+02]
 [3.270000e+00 6.800000e+02]
 [8.500000e+00 6.300000e+02]
 [9.899999e+00 4.700000e+02]
 [9.580000e+00 6.150000e+02]
 [2.060000e+00 3.450000e+02]
 [4.600000e+00 6.780000e+02]
 [2.400000e+00 4.800000e+02]
 [6.250000e+00 1.120000e+03]
 [4.700000e+00 1.035000e+03]
 [2.120000e+00 3.420000e+02]
 [4.000000e+00 8.300000e+02]
 [6.900000e+00 1.515000e+03]
 [5.600000e+00

In [18]:
print(X_train_filter)

[[  13.    660.  ]
 [   5.    515.  ]
 [   4.5   660.  ]
 [  11.75  620.  ]
 [   3.7  1020.  ]
 [   2.7   312.  ]
 [   2.62  450.  ]
 [   3.17  750.  ]
 [   4.4   550.  ]
 [   5.68 1185.  ]
 [   3.3   710.  ]
 [   2.08  365.  ]
 [   7.6   640.  ]
 [   5.6  1265.  ]
 [   4.6   392.  ]
 [   6.38  970.  ]
 [   4.8  1195.  ]
 [  10.52  675.  ]
 [   5.7   580.  ]
 [   2.94  672.  ]
 [   3.4   750.  ]
 [   4.6   880.  ]
 [   2.15  290.  ]
 [   3.8  1035.  ]
 [   4.9   415.  ]
 [   2.9   428.  ]
 [   2.85  718.  ]
 [  10.26  685.  ]
 [   5.   1280.  ]
 [   5.25 1290.  ]
 [   3.95 1285.  ]
 [   8.21  855.  ]
 [   4.32  735.  ]
 [   3.84  990.  ]
 [   2.6   937.  ]
 [   5.5   510.  ]
 [   3.8   428.  ]
 [   5.75 1510.  ]
 [   7.65  625.  ]
 [   2.6   380.  ]
 [   5.64 1065.  ]
 [   4.35  520.  ]
 [   3.94  352.  ]
 [   2.95  355.  ]
 [   5.04  885.  ]
 [   2.5   625.  ]
 [   4.5   915.  ]
 [   6.13  795.  ]
 [   3.    466.  ]
 [   3.58  830.  ]
 [   3.93 1015.  ]
 [   5.7   560.  ]
 [   3.9   7

In [ ]:
print(X_train_filter[:36] == X_test_filter)

In [22]:
print(X_train[0])

[1.434e+01 1.680e+00 2.700e+00 2.500e+01 9.800e+01 2.800e+00 1.310e+00
 5.300e-01 2.700e+00 1.300e+01 5.700e-01 1.960e+00 6.600e+02]


In [23]:
print(X_train_filter[0])

[ 13. 660.]


### Wrapper Methods

### RFE (Recursive Feature Elimination)

In [25]:
model = LogisticRegression(solver='lbfgs', max_iter=5000)
rfe_selector = RFE(model, n_features_to_select=2)
X_train_rfe = rfe_selector.fit_transform(X_train,y_train)
X_test_rfe = rfe_selector.transform(X_test)

print("Fitur yang dipilih dengan Wrapper Methods:", rfe_selector.get_support(indices=True))

Fitur yang dipilih dengan Wrapper Methods: [0 6]


### Embedded Methods

In [36]:
# Menggunakan Random Forest untuk mendapatkan fitur penting

rf_model = RandomForestClassifier(n_estimators=100, random_state=42)
rf_model.fit(X_train, y_train)

importances = rf_model.feature_importances_
print(importances)
indices = np.argsort(importances)[::-1]
print(indices)

print(max(importances))
print(min(importances))

[0.11239774 0.03570276 0.02128206 0.03242488 0.0368407  0.02927859
 0.20229342 0.01351525 0.02356092 0.17120218 0.07089132 0.11156432
 0.13904587]
[ 6  9 12  0 11 10  4  1  3  5  8  2  7]
0.20229341635663622
0.013515250584037197


In [33]:
# ambang batas

treshold = 0.05

important_features_indices = [i for i in range(len(importances)) if importances[i] >= treshold]

print(important_features_indices)

[0, 6, 9, 10, 11, 12]


In [35]:
X_important = X_train[:, important_features_indices]  # Hanya fitur penting dari data pelatihan
X_test_important = X_test[:, important_features_indices]  # Hanya fitur penting dari data pengujian
 
# Mencetak fitur yang dipilih
print("Fitur yang dipilih dengan Embedded Methods (di atas ambang batas):")
for i in important_features_indices:
    print(f"{data.feature_names[i]}: {importances[i]}")
 
# X_important sekarang berisi hanya fitur penting
print("\nDimensi data pelatihan dengan fitur penting:", X_important.shape)
print("Dimensi data pengujian dengan fitur penting:", X_test_important.shape)

Fitur yang dipilih dengan Embedded Methods (di atas ambang batas):
alcohol: 0.11239773542143086
flavanoids: 0.20229341635663622
color_intensity: 0.1712021830864957
hue: 0.07089132259413944
od280/od315_of_diluted_wines: 0.1115643167260497
proline: 0.13904586955351153

Dimensi data pelatihan dengan fitur penting: (142, 6)
Dimensi data pengujian dengan fitur penting: (36, 6)


### Evaluasi dengan fitur terpilih dari masing-masing metode

In [37]:
def evaluate_model(X_train, X_test, y_train, y_test, model):
    model.fit(X_train, y_train)
    accuracy = model.score(X_test, y_test)
    return accuracy

In [38]:
    # Model Logistic Regression untuk Filter Methods
    logistic_model_filter = LogisticRegression(max_iter=200)
    accuracy_filter = evaluate_model(X_train_filter, X_test_filter, y_train, y_test, logistic_model_filter)
     
    # Model Logistic Regression untuk Wrapper Methods
    logistic_model_rfe = LogisticRegression(max_iter=200)
    accuracy_rfe = evaluate_model(X_train_rfe, X_test_rfe, y_train, y_test, logistic_model_rfe)
     
    # Model Random Forest untuk Embedded Methods
    accuracy_rf = evaluate_model(X_important, X_test_important, y_train, y_test, rf_model)

In [40]:
print(f"\nAkurasi Model dengan Filter Methods: {accuracy_filter:.2f}")
print(f"Akurasi Model dengan Wrapper Methods: {accuracy_rfe:.2f}")
print(f"Akurasi Model dengan Embedded Methods: {accuracy_rf:.2f}")


Akurasi Model dengan Filter Methods: 0.89
Akurasi Model dengan Wrapper Methods: 0.94
Akurasi Model dengan Embedded Methods: 1.00


## Scaling

In [3]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler
    
# Contoh data
data = [[10], [2], [30], [40], [50]]
    
# Min-Max Scaling
min_max_scaler = MinMaxScaler()
scaled_min_max = min_max_scaler.fit_transform(data)
print("Min-Max Scaling:\n", scaled_min_max)
    
# Standardization
standard_scaler = StandardScaler()
scaled_standard = standard_scaler.fit_transform(data)
print("\nStandardization:\n", scaled_standard)

Min-Max Scaling:
 [[0.16666667]
 [0.        ]
 [0.58333333]
 [0.79166667]
 [1.        ]]

Standardization:
 [[-0.91133616]
 [-1.35589038]
 [ 0.2000494 ]
 [ 0.75574218]
 [ 1.31143496]]
